### ISSUE TITLE
[P-2] "All" label for Community filter should be "Any"

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#235]
**Description:**
The Community filter on the top level Places page should use “- Any -” as the “match all” label. Currently the label is “- Please select -”.
Compare
http://yukon-ca-d10.sp8.kellett.ca/places: “- Please select -” x
https://yukon.ca/en/places/ : “- Any -” white_check_mark
![image](https://github.com/ytgov/yukon-ca/assets/123640502/71b1cd2e-acba-49b2-9f5f-9c36c012d6a8)

**Task:**
Replace “- Please select -” by “- Any -”

**Deliverable:**
The Community filter on the top level Places page should use “- Any -” as the “match all” label.

**Comment by w3creatives** [comment]
Done.

https://yukon-new-d10.w3creatives.com/docroot/en/places

**Comment by leeomara** [comment]
- ✅ Looks good on W3 test server
- ❌ Despite running on `2a3bf4b6c0` (code from #641), on UAT, this still shows "Please select"
