### ISSUE TITLE
[P-2] "Warning" field is wrong

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#258]
**Description:**
Warning field formatting should be plain text (D10 currently has it as rich text)
Warning field description says the value won’t be displayed, but it is.
https://test-yukon-drupal-10.pantheonsite.io/node/36080/edit

Current description reads:

Use for sites where there is an alert, or high priority information for potential visitors. This will not show up on http://yukon.ca/

Should instead read:

Use for sites where there is an alert, or high priority information for potential visitors.

**Task:**
Fix "Warning" field

**Deliverable:**
"Warning" field Should be the same as on D7

**Comment by w3creatives** [comment]
Done:

https://yukon.ca/outdoor-recreation-and-wildlife/camping/site/congdon-creek-campground
https://yukon-new-d10.w3creatives.com/docroot/en/outdoor-recreation-and-wildlife/camping/site/congdon-creek-campground

**Comment by leeomara** [comment]
❌ not fixed: "This will not show up on http://yukon.ca/" still showing (EF)

**Comment by lgontard** [comment]
@w3creatives @leeomara Unresolved. The warning field on campground pages stills appears as rich text instead of plain text

**Comment by lgontard** [comment]
@w3creatives @leeomara This is resolved in W3C environment

**Comment by leeomara** [comment]
This looks good in dev.
