### ISSUE TITLE
[P-2] Backcountry campgrounds show wrong fields

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#263]
**Description:**

_Should show:_
Region
Total sites
Site description

_Not_
Registration required
Totals sites
Pull through
Serviced
etc.
Empty “Map download” field should not be listed.

Example:

D10 https://test-yukon-drupal-10.pantheonsite.io/outdoor-recreation-and-wildlife/camping/site/thirty-miletaga-shaw-jadali-lower-laberge-campground
D7 https://yukon.ca/en/outdoor-recreation-and-wildlife/camping/site/thirty-mile-lower-laberge

**Task:**
Fix backcountry campgrounds fields visibility

**Deliverable:**
Backcountry campgrounds fields should be the same as on D7

**Comment by w3creatives** [comment]
Fixed:

https://yukon.ca/en/outdoor-recreation-and-wildlife/camping/site/kookatsoon-lake-recreation-site

**Comment by leeomara** [comment]
- ✅ This looks good on W3 Creatives test site.
- ❌ On UAT, with code from `9303e6f64ca`, from Fri Oct 11 2024. This is still showing unwanted fields (e.g. Registration required, pull through) and a header "Backcountry campground"

![Screenshot 2024-10-15 at 2 22 09 PM](https://github.com/user-attachments/assets/714220cf-6936-4fa4-b413-0e8433c0bb17)

**Comment by w3creatives** [comment]
It should work with the latest PR:

https://yukon.ca/en/outdoor-recreation-and-wildlife/camping/site/kookatsoon-lake-recreation-site
https://yukon-new-d10.w3creatives.com/docroot/en/outdoor-recreation-and-wildlife/camping/site/kookatsoon-lake-recreation-site

**Comment by leeomara** [comment]
Looks good on UAT.
