### ISSUE TITLE
[P-3] Day use rec sites wrong fields

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#265]
**Description:**
Campgrounds that are “Recreation site (day use only)” displays different fields.

Should not show:
total site
pull through
registration required

D10 https://test-yukon-drupal-10.pantheonsite.io/outdoor-recreation-and-wildlife/camping/site/kookatsoon-lake-recreation-site
D7 https://yukon.ca/en/outdoor-recreation-and-wildlife/camping/site/kookatsoon-lake

**Task:**
Fix displaying wrong fields

**Deliverable:**
Campgrounds that are “Recreation site (day use only)” should display the same fields as D7

**Comment by w3creatives** [comment]
Fixed:

https://yukon.ca/en/outdoor-recreation-and-wildlife/camping/site/kookatsoon-lake-recreation-site

**Comment by leeomara** [comment]
- ✅ This looks good on W3 Creatives test site.
- ❌ On UAT, with code from 9303e6f64ca, from Fri Oct 11 2024. This is still showing unwanted fields (e.g. Registration required, Total sites, Pull through) and a header "Recreation site (day use only)"

**Comment by w3creatives** [comment]
It should work with the latest PR:

https://yukon.ca/en/outdoor-recreation-and-wildlife/camping/site/kookatsoon-lake-recreation-site
https://yukon-new-d10.w3creatives.com/docroot/en/outdoor-recreation-and-wildlife/camping/site/kookatsoon-lake-recreation-site

**Comment by leeomara** [comment]
This still appears broken on UAT (which has 382143c0, from Oct 25). I'll have to re-test after updating again.

**Comment by leeomara** [comment]
Still not working on UAT (based on 60b8c00, from Nov 2, which has #666).

<img width="401" alt="Screen Shot 2024-11-02 at 12 02 38 PM" src="https://github.com/user-attachments/assets/9d743c1b-436c-41e2-80a2-c49736a87e0f">

**Comment by w3creatives** [comment]
Review link: 

https://yukon-new-d10.w3creatives.com/docroot/outdoor-recreation-and-wildlife/camping/site/kookatsoon-lake-recreation-site

**Comment by leeomara** [comment]
Looks good on UAT.
