### ISSUE TITLE
Consistent date formatting

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#465]
Yukon government has guidance for [Date and time from the style guide](https://guide.yukon.ca/en/content-and-design/government-yukon-style-guide/z-style/date-and-time).

We would like D10 to be more consistent about date formatting, in both English and French.

I propose that we focus on a small number of date formats, 

E.g.

| format | English | French |
|---------|-----------|-----------|
| long | Monday, June 3, 2024 | Lundi 3 juin 2024 |
| medium | June 3, 2024 | 3 juin 2024 |
| short | 2024-06-03 | 2024-06-03 |

**Comment by leeomara** [comment]
In order to better understand what dates need this formatting, we can look at reports of date fields, also use of date values in Views and other displays.

**Comment by adrianrylski** [comment]
@leeomara Ok, I will add a ticket for us to report on it. Thank you

**Comment by adrianrylski** [comment]
@leeomara we have identified the following date format usage by going over the config files:


![Image](https://github.com/ytgov/yukon-ca/assets/169937189/8d43d34a-ecec-44c9-84bb-bf484a36a14c)

**Comment by adrianrylski** [comment]
1. All date-formats were updated according to "Date and time from the style guide":https://guide.yukon.ca/en/content-and-design/government-yukon-style-guide/z-style/date-and-time. Only _HTML *_ were skipped.
2. After update the following formats are used on site

| *machine name* | *Old name* | *New name* | *Example EN* | *Example FR* |
|--------|--------|--------|--------|--------|
| long_format | Long | Long | Tuesday, July 2, 2024 | mardi 2 juillet 2024 |
| long | Default long date | Long with Time | Tuesday, July 2, 2024 - 3:15 pm | mardi 2 juillet 2024 - 15 h 15 |
| medium_format | Medium *new | Medium | July 2, 2024 | 2 juillet 2024|
| medium | Default medium date | Medium with Time | July 2, 2024 - 3:15 pm | 2 juillet 2024 - 15 h 15 |
| short_format | Short *new | Short | 2024-02-07 | 2024-02-07 |
| short | Default short date | Short with Time | 2024-02-07 - 3:15 pm | 2024-02-07 - 15 h 15 |
| time_am_pm | Time am/pm | Time am/pm | 3:15 pm | 15 h 15 |
| fallback | Fallback date format | Fallback date format | Tuesday July 2 2024 - 3:15 pm | mardi 2 juillet 2024 - 15 h 15 |

3. The following date-format transition were performed:
- long_format - > medium_format
- yg_long - > medium_format
- long_with_time - > medium

4. Removed date-formats
- Long with Time (long_with_time)
- Long (yg_long)

h2.  Links and other info:

* Merge Request: https://github.com/ytgov/yukon-ca/pull/510
* Link to test: https://dev-64840-2-yukon-drupal-10.pantheonsite.io
* Current environment: (dev-64840 mutlidev)

h2.  Instructions to test:

* EN - https://dev-64840-2-yukon-drupal-10.pantheonsite.io/en/admin/config/regional/date-time
* FR - https://dev-64840-2-yukon-drupal-10.pantheonsite.io/fr/admin/config/regional/date-time

Check if displayed dates matching guide:
 
* EN - https://guide.yukon.ca/en/content-and-design/government-yukon-style-guide/z-style/date-and-time
* FR - https://guide.yukon.ca/fr/contenu-et-design/guide-de-redaction/guide-de-redaction/date-et-heure

h2.  Affected pages/Information
(Notes a rough but maybe they can be helpful)

h3. Transition information

*long_format -> medium_format*
        
1. `Documents` content type ('Last updated' field)
Examples
* Mutlidev - https://dev-64840-2-yukon-drupal-10.pantheonsite.io//en/fair-wage-schedule-2024
* D10 DEV - https://dev-yukon-drupal-10.pantheonsite.io/en/fair-wage-schedule-2024
* D7 - https://yukon.ca/en/fair-wage-schedule-2024
        
2. 'Documents Browse' (/documents) page
NEED UPDATE in appropriate task - #64784 or in new task
    
*yg_long -> medium_format*

1. `Campground and Recreation Site` content type (Serviced end date, Serviced end date, 'Gate closed date' fields)
Examples,
* Multidev - https://dev-64840-2-yukon-drupal-10.pantheonsite.io//en/outdoor-recreation-and-wildlife/camping/site/tatchun-creek-campground
* D10 DEV - https://dev-yukon-drupal-10.pantheonsite.io/en/outdoor-recreation-and-wildlife/camping/site/tatchun-creek-campground
* D7 - https://yukon.ca/en/outdoor-recreation-and-wildlife/camping/site/tatchun-creek-campground
        
2. Places content type
* opening_and_closing_times (paragraph) => (paragraph) holiday_times => node directory_records_places => (paragraph) opening_times => node directory_records_places
        
3. Blog listing (blog_listing) view Recent blog posts (block_1) display.
* Date (created) is excluded from display
* Block isn't working at all.
        
4. Event listing (event_listing) view, both blocks.
https://dev-64840-2-yukon-drupal-10.pantheonsite.io//en/admin/structure/views/view/event_listing/edit/block_1
We don't have this page working yet:
* Multidev - https://dev-64840-2-yukon-drupal-10.pantheonsite.io//en/arts-and-culture/events
* D10 DEV - https://dev-yukon-drupal-10.pantheonsite.io/en/arts-and-culture/events
* D7 - https://yukon.ca/en/arts-and-culture/events
        
5. Events Listing (events_listing) view, Featured Events display
* Block isn't in use.
        
6. News listing (news_listing) view

News (block_news_listing) views display
* Multidev - https://dev-64840-2-yukon-drupal-10.pantheonsite.io//en/news
* D10 DEV - https://dev-yukon-drupal-10.pantheonsite.io/en/news - doesn't work yet
* D7 - https://yukon.ca/en/news

News Listing (block_department_latest_news) views display - at the Departments node page.
* Multidev - https://dev-64840-2-yukon-drupal-10.pantheonsite.io//en/yukon-housing-corporation
* D10 DEV - https://dev-yukon-drupal-10.pantheonsite.io/en/yukon-housing-corporation
* D7 - https://yukon.ca/en/yukon-housing-corporation
        
7. Comment date
* Multidev - https://dev-64840-2-yukon-drupal-10.pantheonsite.io//en/blogs/geomatics-and-digital-mapping/update-geoyukon-biological-mapservice-0
* D10 DEV - https://dev-yukon-drupal-10.pantheonsite.io/en/blogs/geomatics-and-digital-mapping/update-geoyukon-biological-mapservice-0 - Add new comment form isn't working
* D7 (pantheon copy) - https://yukon.cms-uat.yukon.ca/en/digital-blog/test-blog-2

*long_with_time -> medium*

1. Event content type, field_event_start_time.
* Mutlidev - https://dev-64840-2-yukon-drupal-10.pantheonsite.io//en/events/managing-conflict-after-separation-or-divorce-1
* D10 DEV - https://dev-yukon-drupal-10.pantheonsite.io/en/events/managing-conflict-after-separation-or-divorce-1
* D7 - https://yukon.ca/en/events/summer-series-sleep-solutions-steps-improving-sleep-hygiene-hosted-sleep-wellness

2. Event listing (events_listing) view
Events (block_events_listing) display field_event_start_time field
We don't have this page properly working yet:
* Mutlidev - https://dev-64840-2-yukon-drupal-10.pantheonsite.io//en/places-2
* D10 DEV - https://dev-yukon-drupal-10.pantheonsite.io/en/places-2
* D7 - https://yukon.ca/en/events

**Comment by leeomara** [comment]
Most of these look great. Some of the ones that have ranges seem to be missing a space after the word "to".

See
- https://dev-64840-2-yukon-drupal-10.pantheonsite.io//en/events/managing-conflict-after-separation-or-divorce-1
- https://dev-64840-2-yukon-drupal-10.pantheonsite.io/en/places-2

Notably, Campgrounds, which have ranges seem fine. E.g. https://dev-64840-2-yukon-drupal-10.pantheonsite.io/en/outdoor-recreation-and-wildlife/camping/site/tatchun-creek-campground

![Yukon ca d10 465 Screenshot 2024-07-12 at 2 37 27 PM](https://github.com/user-attachments/assets/1f93c503-103d-455d-b38e-6b1048d94889)

![Yukon ca d10 465 Screenshot 2024-07-12 at 2 37 17 PM](https://github.com/user-attachments/assets/ab3be8c7-bba7-4ac1-8467-090fc7e292ff)

**Comment by adrianrylski** [comment]
@leeomara, Most likely, this is coming from theming post-date format change.  I will add a new ticket for the new sprint to adjust when needed.

**Comment by adrianrylski** [comment]
@leeomara, I created a new ticket to address the issues with theming. #520. Work so far will be deployed to DEV/master as per out conversation last Monday.

**Comment by leeomara** [comment]
This issue/task will be taken over by W3 Creatives. No further work by EW is required for this issue.

**Comment by leeomara** [comment]
- ✅ Config look correct, at /en/admin/config/regional/date-time
- ✅ Document
	- ✅ Document date looks good. E.g. https://yukond10.cms-uat.yukon.ca/en/fair-wage-schedule-2024
	- ✅ Documents browse look good. E.g. https://yukond10.cms-uat.yukon.ca/en/documents
- ✅ Campground and Recreation Site look good. E.g. https://yukond10.cms-uat.yukon.ca/en/outdoor-recreation-and-wildlife/camping/site/tatchun-creek-campground
- ✅ Places
	- ✅ Formatting of time is improved.
	- 🟠 Opening times are shifted (timezone issue?) I'll open a separate issue for this.
	    - D7: "9 a.m. to 12 p.m." https://yukon.ca/en/places/whitehorse-walk-clinic 
	    - D10: "11:59 pm to 2:59 am" https://yukond10.cms-uat.yukon.ca/en/node/22764
	    - See also https://yukond10.cms-uat.yukon.ca/en/places/sheriffs-office vs https://yukon.ca/en/sheriff-office
- ✅ Blog
	- ✅ Blog listing looks good. E.g. https://yukond10.cms-uat.yukon.ca/en/blogs/digital-information-and-services
	- ✅ Blog post looks good. E.g. https://yukond10.cms-uat.yukon.ca/en/digital-blog/migration-milestone-reached
	- ❓Blog comment: unable to test, could not find migrated comment, could not create new comment.
- ❌ Events
	- ❌ Events page display of time now seems broken. Does not show a range, only one side of time.
		- D7: 👍 "Time: 8 am to 4:30 pm" https://yukon.ca/en/events/gathering-over-food-knowledge-sharing-event?date=2024-11-04
		- D10: 👎 "Time: 14:11 pm" https://yukond10.cms-uat.yukon.ca/en/events/gathering-over-food-knowledge-sharing-event
	- ❌ Events listing has same issue as Events page (above)
		- D10: "November 4, 2024 to 3:30 pm" (no start time) https://yukond10.cms-uat.yukon.ca/en/events
    	- This was previously working better. See above [comment from July 12](https://github.com/ytgov/yukon-ca/issues/465#issuecomment-2226393438)
- 🟠 News
	- ✅ News looks good https://yukond10.cms-uat.yukon.ca/en/news
	- ✅ News listing on department page looks good. E.g. https://yukond10.cms-uat.yukon.ca/en/your-government/departments/department-economic-development
 	- ❌ News page has wrong date format. E.g. "Published 01/10/2024" https://yukond10.cms-uat.yukon.ca/en/news/statement-minister-mcphee-national-seniors-day

**Comment by w3creatives** [comment]
We have done the following updates:

- Created form Blog comments.
- Place timing fixed in - #608.
- News page date format is fixed.
- French Translation - #237 Done on New-d10

**Comment by leeomara** [comment]
- ❌ News pages still show date in incorrect format - not fixed ("Published 26/08/2024" instead of "Published 2024-08-26") 
- ❌ Events pages display a "0" before single-digit days in the date (i.e. shows "May 07, 2020" instead of "May 7, 2020") 
 
See: https://yukon-new-d10.w3creatives.com/docroot/en/news/yukon-firefighters-meet-in-dawson-for-training-conference and https://yukon-new-d10.w3creatives.com/docroot/en/events/managing-conflict-after-separation-or-divorce-1

**Comment by leeomara** [comment]
- ❌ News pages still show date in incorrect format - not fixed ("Published 26/08/2024" instead of "Published 2024-08-26")
    - See: https://yukon-new-d10.w3creatives.com/docroot/en/news/yukon-firefighters-meet-in-dawson-for-training-conference 
- ❌ Events pages display a "0" before single-digit days in the date (i.e. shows "May 07, 2020" instead of "May 7, 2020")
    - See: https://yukon-new-d10.w3creatives.com/docroot/en/events/managing-conflict-after-separation-or-divorce-1
- Month translation:
    - I noticed month not translated like here: [Annexe des salaires équitables 2024 | Yukon.ca (w3creatives.com)](https://yukon-new-d10.w3creatives.com/docroot/fr/annexe-des-salaires-equitables-2024). 
    - Also the first letter of month in French is capitalized and it shouldn't [Communiqués de presse | Yukon.ca (w3creatives.com)](https://yukon-new-d10.w3creatives.com/docroot/fr/communiques-de-presse)
    - The above are now a new issue: https://github.com/ytgov/yukon-ca/issues/645

Medium date format seems fine except when a time is added as here: [Events | Yukon.ca (w3creatives.com)](https://yukon-new-d10.w3creatives.com/docroot/en/arts-and-culture/events)+ that format for the event is not as it should be.

**Comment by w3creatives** [comment]
Please review:

https://yukon-new-d10.w3creatives.com/docroot/en/news/yukon-firefighters-meet-in-dawson-for-training-conference and https://yukon-new-d10.w3creatives.com/docroot/en/events/managing-conflict-after-separation-or-divorce-1

**Comment by lgontard** [comment]
@leeomara @w3creatives This is resolved in YG UAT
