### ISSUE TITLE
Departments

### ISSUE THREAD

**Issue by w3creatives** [ytgov/yukon-ca#565]
**Design and Functionality:**

1. The font size >> page heading in D10 are bigger. (Done)
2. Top right side aurora should be removed. (Done)
3. Other headings font size and weights are different. (Done)
4. Under Services and Information Grid Blocks - The 3 container blocks have text underlined whereas in D7 the text only underlines on hover. (Done)
5. Under Services and Information Grid Blocks - Padding is missing. (Done)
6. Latest News >> all item headings are underlined whereas in D7 its on hovering and also the news content/excerpt under each heading is missing. (Done)
7. Minister Responsible - Design broken. (Done)
8. Under Minister Responsible - D10 text is without accordion as compared to D7. (Done)
9. Left sidebar design needs update for design and extra content should be removed. (Done)
10. First accordion should be open by default. (Done)
https://yukon-new-d10.w3creatives.com/docroot/en/department-highways-public-works

**Content & Migration:**

11. Left side bar displays different sub pages. (Done)
12. Missing Migrations >> accordion panels. (Done)
13. Services and Information links on French version goes to English: (Done)
https://yukon-new-d10.w3creatives.com/docroot/fr/ministere-voirie-travaux-publics

**Translation:**

14. The French translation is not complete in the French page. (Done)

**Reference Links:**

https://yukon.ca/en/department-highways-public-works
https://dev-yukon-drupal-10.pantheonsite.io/en/department-highways-public-works
https://yukon-new-d10.w3creatives.com/docroot/en/department-highways-public-works

**Comment by leeomara** [comment]
All the listed items looks good.

I noticed that the breadcrumb wraps quite a bit sooner than needed (and sooner than in D7).

Should I create a new/separate issue for this?

![Screenshot 2024-09-26 at 10 50 04 AM](https://github.com/user-attachments/assets/00541a24-cf5f-4da6-b444-46bacb6859ef)

**Comment by w3creatives** [comment]
> All the listed items looks good.
> 
> I noticed that the breadcrumb wraps quite a bit sooner than needed (and sooner than in D7). Should I create a new/separate issue for this? (this isn't limited to Departments)
> 
> ![Screenshot 2024-09-26 at 10 50 04 AM](https://github.com/user-attachments/assets/00541a24-cf5f-4da6-b444-46bacb6859ef)

Fixed.

**Comment by w3creatives** [comment]
Breadcrumbs issue is fixed.

**Comment by leeomara** [comment]
When I look at https://yukon-new-d10.w3creatives.com/docroot/en/department-highways-public-works I still see the same breadcrumb issue (as in the screenshot above). Am I looking at the wrong site?

I don't know why `.breadcrumb` has a `width: 60%`?

**Comment by leeomara** [comment]
Looks good on W3 server.

**Comment by leeomara** [comment]
Looks good on UAT.
