### ISSUE TITLE
Campaign pages

### ISSUE THREAD

**Issue by w3creatives** [ytgov/yukon-ca#566]
https://yukon-new-d10.w3creatives.com/docroot/en/decide-you-ride-drive-sober
https://yukon.ca/en/decide-you-ride-drive-sober

https://yukon-new-d10.w3creatives.com/docroot/fr/consommer-ou-conduire-choisis
https://yukon.ca/fr/consommer-ou-conduire-choisis

* Campaign pages missing most of things
* D10 English page shows French text
* From top the second section with 3 icon blocks (Campaign Nav block) on click don’t work both in English and French pages
* “Pour En Savoir” Plus Button in Grey Colour Block >> Not working in D10. When other pages were checked the buttons were not working there as well.
* D10 French page Last Block on page bottom Follow the campaign on is in English

**Comment by leeomara** [comment]
1. ❌ top design is still missing.
2. ✅ fixed in the english side, does not appear on the French side.
3. ❌ not fixed.
4. ❌ not fixed, both EN and FR
5. ❌ not fixed. I check a recent new engagement and it is not migrated.
6. ✅ fixed.
7. Skipped for now. 
8.❌ not fixed, missing August 16 and 23 updates in French
9. ✅ fixed!

**Comment by w3creatives** [comment]
1. Should be working.
3. Its a docroot issue in the URL. It should in UAT.
4. Done
5. Done
8. Done

**Comment by leeomara** [comment]
❌ No 7 not fixed

![image (11)](https://github.com/user-attachments/assets/fdb558bd-5da8-40f7-94a2-7664fa2cba6b)

**Comment by lgontard** [comment]
@leeomara @w3creatives #7 is unresolved" Follow the campaign on" appears in Eng on the Fre side
<img width="611" alt="image" src="https://github.com/user-attachments/assets/05769de6-ce5e-43f7-86b6-15a2625e003b">

**Comment by w3creatives** [comment]
Please review:

https://yukon-new-d10.w3creatives.com/docroot/fr/consommer-ou-conduire-choisis

**Comment by lgontard** [comment]
@w3creatives @leeomara This is resolved in W3C environment

**Comment by w3creatives** [comment]
Please close if completed.

**Comment by lgontard** [comment]
The "Follow the campaign on" appears in Fre on the Fre side
