### ISSUE TITLE
Campaign page formatting

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#594]
Jump points are not consistent in size. 

This is the content

> - What is a community wildfire protection plan?
> - What you can do to reduce wildfire risk
> - Your community’s plan

Compare:
- D10 https://yukon-new-d10.w3creatives.com/docroot/en/emergencies-and-safety/wildfires/community-wildfire-protection-plans vs. 
- D7 https://yukon.ca/en/emergencies-and-safety/wildfires/community-wildfire-protection-plans

at smaller screen sizes, different behaviour vs. D7 (which linearizes at some point)

**Comment by w3creatives** [comment]
This is fixed.

**Comment by leeomara** [comment]
This looks better, but is still not as good as what we had in D7.

At narrow sizes (e.g. < 690px), the jump links now display (in D10) in large centre-aligned boxes wit the icon above the text. In D7, the boxes are left-aligned with the icon on the same line as the text.

<img width="672" alt="594-jumplinks-narrow" src="https://github.com/user-attachments/assets/fdcdd752-166a-469c-aed9-b60829b19105">

**Comment by w3creatives** [comment]
This has been fixed and will be included in the next PR.

**Comment by w3creatives** [comment]
Please test let us know if it got fixed in the recent migration.

**Comment by leeomara** [comment]
This looks good on the W3 Creatives test site.

**Comment by leeomara** [comment]
This looks good on UAT.
