### ISSUE TITLE
On mobile: categories are laid out in 3-column grid

### ISSUE THREAD

**Issue by lgontard** [ytgov/yukon-ca#812]
On mobile, landing pages display the subcategories (Secondary content) as a 3-column grid. This should display as a single column on narrower displays.

Compare:
- D10: https://yukon.ca/en/education-and-schools/
- D7: https://d7.yukon.ca/en/education-and-schools/

![image](https://github.com/user-attachments/assets/b47837a5-d7cd-42de-824b-51dfe4f8d825)

**Comment by w3creatives** [comment]
This is fixed. Please review - #820

**Comment by lgontard** [comment]
I'm still seeing 3 columns on landing pages (safari and chrome on iphone)
